# Site wide configuration

title:            Fred's Notes
locale:           en_AU
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Friedrich "Fred" Clausen
  avatar: me_cropped.jpg
  bio: "I am a build and infra automation developer working to become a better all-round developer"
  email: ftclausen@gmail.com 
  github: ftclausen
  stackoverflow: http://stackoverflow.com/users/1300307/fred-clausen
  linkedin: friedrichclausen
  google:
    plus: #username
    analytics: UA-42775813-1
    verify: 
    ad-client: 
    ad-slot: 
  serverfault: http://serverfault.com/users/127243/fred-clausen
  superuser: http://superuser.com/users/164635/fred-clausen

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
