name: Fred's Notes
markdown: redcarpet
highlighter: true
redcarpet:
    extensions: [ "tables", "with_toc_data", "fenced_code_blocks" ]
analytics :
  provider : google
  google : 
      tracking_id : 'UA-42775813-1'
